name: Publish Python Package

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'  # Trigger only if setup.py changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Extract Version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if Version is Already on PyPI
        id: check_version
        run: |
          EXISTS=$(curl -s https://pypi.org/pypi/${{ github.event.repository.name }}/json | jq -r --arg ver "$VERSION" '.releases[$ver] | if . then "yes" else "no" end')
          echo "EXISTS=$EXISTS" >> $GITHUB_ENV

      - name: Build the Package
        if: env.EXISTS == 'no'
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: env.EXISTS == 'no'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Success Message
        if: env.EXISTS == 'no'
        run: echo "Version $VERSION successfully published to PyPI 🎉"
